#The script for reading in .fast5 files with multiple reads generated by guppy.

bucketDir=s3://deepmod-benchmark/miten-test-data/fast5/
fast5=($(aws s3 ls ${bucketDir} | grep "fast5" | awk '{print $4}'))

